import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <header className="w-full bg-gray-800 text-white py-4 text-center">
            <h1>Header Dummy</h1>
          </header>
          <main>
            {children}
          </main>
          <footer className="w-full bg-gray-900 text-white py-4 text-center mt-8">
            <p>Footer Dummy</p>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
